[project]
name = "coqui-tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.11.0"
dependencies = [
    "torch==2.5.1",
    "transformers==4.41.0",
    "tts>=0.22.0",
]
